### ISSUE TITLE
Program did not complete

### ISSUE THREAD

**Issue by acarcher** [nrbrase/WebScraper#50]
Using windows 10 64 bit

When selecting new york, I let the program run for about 5 minutes and it never returned any addresses.

**Comment by kimdobert** [comment]
@acarcher We're working on optimizing our runtime, as of right now it takes much longer than 5 minutes to gather information from New York as there are many cities in New York. If you didn't see a window pop up telling you the program complete then the program did not complete and you will not see any addresses.
